apiVersion: v1
kind: Pod
metadata:
  name: combined-init-pod
  labels:
    app: combined-init
spec:
  initContainers:
  # Init container 1: Wait for DNS
  - name: wait-dns
    image: busybox:1.36
    command: ['sh', '-c']
    args:
    - |
      echo "Init 1: Waiting for DNS..."
      until nslookup kubernetes.default.svc.cluster.local; do
        sleep 1
      done
      echo "Init 1: DNS ready"
  # Init container 2: Prepare shared volume
  - name: prepare-data
    image: busybox:1.36
    command: ['sh', '-c']
    args:
    - |
      echo "Init 2: Preparing data..."
      echo "Data prepared by init container" > /shared/data.txt
      echo "Init 2: Data file created"
    volumeMounts:
    - name: shared-storage
      mountPath: /shared
  # Init container 3: Pre-check
  - name: verify-setup
    image: busybox:1.36
    command: ['sh', '-c']
    args:
    - |
      echo "Init 3: Verifying setup..."
      if [ ! -f /shared/data.txt ]; then
        echo "ERROR: data.txt not found"
        exit 1
      fi
      echo "Init 3: Setup verified"
    volumeMounts:
    - name: shared-storage
      mountPath: /shared
  containers:
  - name: main-app
    image: busybox:1.36
    command: ['sh', '-c', 'cat /shared/data.txt && echo "Main container running" && sleep 3600']
    volumeMounts:
    - name: shared-storage
      mountPath: /shared
  volumes:
  - name: shared-storage
    emptyDir: {}
