apiVersion: v1
kind: Pod
metadata:
  labels:
    run: debug-pod
  name: debug-pod
spec:
  containers:
  - command:
    - sleep
    - "3600"
    image: busybox:1.36
    name: debug-pod
  restartPolicy: Never
