apiVersion: v1
kind: Pod
metadata:
  name: sidecar-pod
  labels:
    app: sidecar-demo
spec:
  containers:
  # Main container - writes logs to shared volume
  - name: main-container
    image: busybox:1.36
    command: ["sh", "-c"]
    args:
    - |
      counter=0
      while true; do
        echo "$(date): Main container log entry $counter" >> /var/log/app.log
        counter=$((counter+1))
        sleep 5
      done
    volumeMounts:
    - name: shared-logs
      mountPath: /var/log
  # Sidecar container - tails the log file
  - name: sidecar-container
    image: busybox:1.36
    command: ["sh", "-c", "tail -f /var/log/app.log"]
    volumeMounts:
    - name: shared-logs
      mountPath: /var/log
  volumes:
  - name: shared-logs
    emptyDir: {}
