apiVersion: apps/v1
kind: Deployment
metadata:
  name: broken-liveness
  labels:
    app: broken-liveness
spec:
  replicas: 2
  selector:
    matchLabels:
      app: broken-liveness
  template:
    metadata:
      labels:
        app: broken-liveness
    spec:
      containers:
      - name: web-server
        image: nginx:1.25
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            # path: /healthz  # Wrong path - will return 404
            path: /           # Change to correct path (nginx default page)
            port: 80
          initialDelaySeconds: 10  # Too short - will fail quickly
          periodSeconds: 5
          failureThreshold: 3
