apiVersion: apps/v1
kind: Deployment
metadata:
  name: broken-startup
  labels:
    app: broken-startup
spec:
  replicas: 2
  selector:
    matchLabels:
      app: broken-startup
  template:
    metadata:
      labels:
        app: broken-startup
    spec:
      containers:
      - name: web-server
        image: nginx:1.25
        ports:
        - containerPort: 80
        startupProbe:
          httpGet:
            path: /startup  # Wrong path - will return 404
            port: 80
          initialDelaySeconds: 0
          periodSeconds: 2
          failureThreshold: 5  # Too low - will fail before app starts
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
