apiVersion: apps/v1
kind: Deployment
metadata:
  name: broken-readiness
  labels:
    app: broken-readiness
spec:
  replicas: 2
  selector:
    matchLabels:
      app: broken-readiness
  template:
    metadata:
      labels:
        app: broken-readiness
    spec:
      containers:
      - name: web-server
        image: nginx:1.25
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /ready  # Wrong path - will return 404
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
