apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  labels:
    app: api
type: Opaque
data:
  DB_PASSWORD: c2VjcmV0cGFzc3dvcmQxMjM=    # base64 encoded "secretpassword123"
  API_KEY: YXBpLWtleS1hYmMxMjN4eXo3ODk=    # base64 encoded "api-key-abc123xyz789"
