apiVersion: batch/v1
kind: Job
metadata:
  name: simple-job
  labels:
    app: job-demo
spec:
  completions: 1
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: job-demo
    spec:
      restartPolicy: OnFailure
      containers:
      - name: job-container
        image: busybox:1.36
        command: ["sh", "-c"]
        args:
        - echo "Job completed successfully at $(date)"
      terminationGracePeriodSeconds: 10
